chore: Pull image with PR number previously build
Build image and push it with the PR number tag
and test it in sequential gh action using same pr number

Signed-off-by: Tibor Dudlák <tdudlak@redhat.com>

diff --git a/.github/workflows/gating.yaml b/.github/workflows/gating.yaml
--- a/.github/workflows/gating.yaml
+++ b/.github/workflows/gating.yaml
@@ -2,9 +2,9 @@
 name: Pull request pre-check build & test
 
 on:
-  pull_request:
   push:
     branches: [main]
+  pull_request_target:
 
 jobs:
   pre-commit:
@@ -44,3 +44,53 @@ jobs:
       - name: Run Tests
         run: |
           python src/ipa-tuura/manage.py test
+
+  build:
+    runs-on: ubuntu-latest
+    env:
+      IMAGE_TAG: ${{ github.event.number || github.ref_name  }}
+    name: build the docker image
+    steps:
+      - name: Checkout the repository
+        uses: actions/checkout@v3
+
+      - name: Set up QEMU for docker
+        uses: docker/setup-qemu-action@v2
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Print IMAGE_TAG to be used
+        run: echo "${{ env.IMAGE_TAG }}"
+
+      - name: Print SECRETS as **** if they exists
+        run: echo "username; ${{ secrets.REGISTRY_USERNAME }}"
+
+      - name: Login to quay.io
+        uses: docker/login-action@v2
+        with:
+          registry: quay.io
+          username: ${{ secrets.REGISTRY_USERNAME }}
+          password: ${{ secrets.REGISTRY_TOKEN }}
+
+      - name: Build and push the image with given tag
+        uses: docker/build-push-action@v3
+        with:
+          context: ./src
+          file: ./src/Containerfile  # I would rather use Dockerfile or Dockerfile.base but i will not touch the codebase :D
+          push: true
+          tags: "quay.io/idmops/${{ github.event.repository.name }}:${{github.event.number}}"
+
+  test:
+    name: test the built image
+    runs-on: ubuntu-latest
+    container:
+      image: "quay.io/idmops/${{ github.event.repository.name }}:${{ github.event.number || github.ref_name }}"
+    needs: [pre-commit, test-on-ubuntu, build]
+
+    steps:  # inside container
+      - name: Display Container OS version
+        run: cat /etc/redhat-release || uname -a
+
+      - name: Run basic check for file presence
+        run: file /ipa-tuura/manage.py || echo "/ipa-tuura/manage.py not found"
